build_from:
  aarch64: ghcr.io/usememos/memos:0.26.1
  amd64: ghcr.io/usememos/memos:0.26.1
  #aarch64: ghcr.io/usememos/memos:${BUILD_VERSION}
  #amd64: ghcr.io/usememos/memos:${BUILD_VERSION}
args:
  BUILD_ARCH: "${BUILD_ARCH}"
